%Twitter.Status{} |> Twitter.Status.changeset(%{ id: "PENDING" }) |> Twitter.Repo.insert!()
%Twitter.Status{} |> Twitter.Status.changeset(%{ id: "IGNORED" }) |> Twitter.Repo.insert!()
%Twitter.Status{} |> Twitter.Status.changeset(%{ id: "ACCEPTED" }) |> Twitter.Repo.insert!()
%Twitter.User{} |> Twitter.User.changeset(%{ name: "toran", code: "123" }) |> Twitter.Repo.insert!()
%Twitter.User{} |> Twitter.User.changeset(%{ name: "christopher", code: "456" }) |> Twitter.Repo.insert!()
%Twitter.User{} |> Twitter.User.changeset(%{ name: "brandon", code: "789" }) |> Twitter.Repo.insert!()
